baseurl = "https://example.com"
languageCode = "zh-TW"
defaultContentLanguage = "zh"
title = "上課中"
theme = "hugo-theme-dream"

copyright = "Copyright (c) 2017, g1eny0ung; all rights reserved."

# enableRobotsTXT = true

# googleAnalytics = ""

# disqusShortname = ""

[params]
  author = "冠霖"
  motto = "我肚子餓了!"
  # description = ""
   avatar = "/img/010.jpg"
  
  # email = ""
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""
